#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Current readable production view.

The original historical 0.6.10 source is preserved verbatim as
`build_gaia_06100_hybrid_accent_b1_LEGACY.py`.

The current production behavior is applied deterministically by
`build_gaia_06100_hybrid_accent_b1_R5_PATCHED.py`, including the staged
Core/translation source path, exact-overlap safety, R5 precedence fixes and the
0.6.55 runtime-driven intro / Đ/đ polish.
"""
from build_gaia_06100_hybrid_accent_b1_R5_PATCHED import *

# Batch45 font-gate marker. The actual executable formula lives in the patched
# source generated by R5_PATCHED: (y0 + y1) // 2 - 1
