#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv
from collections import defaultdict
from pathlib import Path

INTEREST={'DMA2_MADR','DMA2_BCR','DMA2_CHCR','GP0'}

def hx(s):
    s=str(s).strip(); return int(s,16) if s.lower().startswith('0x') else int(s)

def load_hits(path):
    rows=[]
    with path.open('r',encoding='utf-8-sig',newline='') as f:
        for r in csv.DictReader(f):
            if r.get('access')!='WRITE' or r.get('hw_name') not in INTEREST: continue
            r['_pc']=hx(r['pc']); r['_fs']=hx(r['func_start']); rows.append(r)
    return rows

def rank(rows):
    groups=defaultdict(list)
    for r in rows: groups[r['_fs']].append(r)
    out=[]
    for fs,hs in groups.items():
        names={r['hw_name'] for r in hs}; score=len(hs)
        score += 120 if 'DMA2_CHCR' in names else 0
        score += 90 if 'DMA2_MADR' in names else 0
        score += 70 if 'DMA2_BCR' in names else 0
        score += 50 if 'GP0' in names else 0
        if {'DMA2_MADR','DMA2_BCR','DMA2_CHCR'} <= names: score += 200
        out.append((score,fs,names,hs))
    out.sort(reverse=True)
    return out

def lua_for(groups,max_routines=16):
    chosen=groups[:max_routines]
    exact=[]
    seen=set()
    for score,fs,names,hs in chosen:
        for r in hs:
            k=(r['_pc'],r['hw_name'],r['source_reg'])
            if k in seen: continue
            seen.add(k); exact.append((score,fs,r))
    lines=[
"-- Auto-generated by Gaia Master B52R24 trace generator",
"-- Requires PCSX-Redux debugger + interpreter. Load in Lua editor/console.",
"gaia_b52r24_bps = gaia_b52r24_bps or {}",
"gaia_b52r24_events = {}",
"gaia_b52r24_armed = false",
"gaia_b52r24_last_madr = nil",
"gaia_b52r24_last_bcr = nil",
"gaia_b52r24_last_chcr = nil",
"gaia_b52r24_seq = 0",
"gaia_b52r24_skip = 0",
"",
"local function gaia24_hex(v) return string.upper(bit.tohex(tonumber(v),8)) end",
"local function gaia24_record(pc, ra, hw, regname, value, fs, score)",
"  gaia_b52r24_seq = gaia_b52r24_seq + 1",
"  local e = {seq=gaia_b52r24_seq, pc=tonumber(pc), ra=tonumber(ra), hw=hw, reg=regname, value=tonumber(value), func=fs, score=score}",
"  gaia_b52r24_events[#gaia_b52r24_events+1] = e",
"  print('GAIA_B52R24 seq='..tostring(e.seq)..' hw='..hw..' pc='..gaia24_hex(e.pc)..' ra='..gaia24_hex(e.ra)..' '..regname..'='..gaia24_hex(e.value))",
"end",
"",
"function gaia_arm24(skip)",
"  gaia_b52r24_events = {}; gaia_b52r24_seq = 0",
"  gaia_b52r24_skip = tonumber(skip or 0) or 0",
"  gaia_b52r24_last_madr = nil; gaia_b52r24_last_bcr = nil; gaia_b52r24_last_chcr = nil",
"  gaia_b52r24_armed = true",
"  print('GAIA B52R24 ARMED: skip=' .. tostring(gaia_b52r24_skip) .. '; enter the target menu now')",
"end",
"function gaia_next24() gaia_arm24(0); PCSX.resumeEmulator() end",
"function gaia_disarm24() gaia_b52r24_armed=false; print('GAIA B52R24 disarmed') end",
"",
"function gaia_save24(prefix)",
"  prefix = prefix or 'GaiaMaster_B52R24'",
"  local tf = assert(io.open(prefix .. '_TRACE.tsv','wb'))",
"  tf:write('seq\\tpc\\tra\\thw\\treg\\tvalue\\tfunc_start\\tscore\\n')",
"  for _,e in ipairs(gaia_b52r24_events) do",
"    tf:write(tostring(e.seq)..'\\t'..gaia24_hex(e.pc)..'\\t'..gaia24_hex(e.ra)..'\\t'..e.hw..'\\t'..e.reg..'\\t'..gaia24_hex(e.value)..'\\t'..gaia24_hex(e.func)..'\\t'..tostring(e.score)..'\\n')",
"  end",
"  tf:close()",
"  local mem = PCSX.getMemPtr()",
"  local rf = assert(io.open(prefix .. '_RAM.bin','wb'))",
"  rf:write(ffi.string(mem,0x200000)); rf:close()",
"  local mf = assert(io.open(prefix .. '_META.txt','wb'))",
"  mf:write('events=' .. tostring(#gaia_b52r24_events) .. '\\n')",
"  mf:write('madr=' .. (gaia_b52r24_last_madr and gaia24_hex(gaia_b52r24_last_madr) or 'NONE') .. '\\n')",
"  mf:write('bcr=' .. (gaia_b52r24_last_bcr and gaia24_hex(gaia_b52r24_last_bcr) or 'NONE') .. '\\n')",
"  mf:write('chcr=' .. (gaia_b52r24_last_chcr and gaia24_hex(gaia_b52r24_last_chcr) or 'NONE') .. '\\n')",
"  mf:close()",
"  print('GAIA B52R24 saved: ' .. prefix .. '_TRACE.tsv + _RAM.bin + _META.txt')",
"end",
"",
"local targets = {"
]
    for score,fs,r in exact:
        lines.append("  {addr=0x%08X, fs=0x%08X, score=%d, hw='%s', reg='%s'},"%(r['_pc'],fs,score,r['hw_name'],r['source_reg']))
    lines += ["}","",
"for i,t in ipairs(targets) do",
"  gaia_b52r24_bps[i] = PCSX.addBreakpoint(t.addr,'Exec',4,'Gaia B52R24 '..t.hw,function()",
"    if not gaia_b52r24_armed then return end",
"    local ok,msg = pcall(function()",
"      local r = PCSX.getRegisters()",
"      local v = 0",
"      if false then v=0"
]
    regs=sorted({r['source_reg'] for _,_,r in exact})
    for reg in regs:
        lines.append("      elseif t.reg == '%s' then v = tonumber(r.GPR.n.%s)"%(reg,reg))
    lines += [
"      end",
"      gaia24_record(r.pc,r.GPR.n.ra,t.hw,t.reg,v,t.fs,t.score)",
"      if t.hw == 'DMA2_MADR' then gaia_b52r24_last_madr=v end",
"      if t.hw == 'DMA2_BCR' then gaia_b52r24_last_bcr=v end",
"      if t.hw == 'DMA2_CHCR' then",
"        gaia_b52r24_last_chcr=v",
"        local start = bit.band(bit.rshift(v,24),1)",
"        local sync = bit.band(bit.rshift(v,9),3)",
"        local dir = bit.band(v,1)",
"        print(string.format('GAIA_B52R24 DMA START? start=%d sync=%d dir=%d',start,sync,dir))",
"        if start == 1 then",
"          if gaia_b52r24_skip > 0 then",
"            gaia_b52r24_skip = gaia_b52r24_skip - 1",
"            gaia_b52r24_events = {}; gaia_b52r24_seq = 0; gaia_b52r24_last_madr=nil; gaia_b52r24_last_bcr=nil; gaia_b52r24_last_chcr=nil",
"            print('Skipped DMA start; remaining skip='..tostring(gaia_b52r24_skip))",
"          else",
"            gaia_b52r24_armed=false; PCSX.pauseEmulator(); print('Paused. Run gaia_save24() now; gaia_next24() continues to the next DMA start.')",
"          end",
"        end",
"      end",
"    end)",
"    if not ok then print('GAIA_B52R24 callback error: '..tostring(msg)); gaia_b52r24_armed=false; PCSX.pauseEmulator() end",
"  end)",
"end",
"print(string.format('GAIA B52R24 loaded %d exact MMIO breakpoints. Run gaia_arm24() before the target menu.',#targets))",
]
    return '\n'.join(lines)+'\n',exact

def selftest(tmp):
    p=tmp/'hits.csv'
    p.write_text('pc,access,hw_name,source_reg,func_start\n0x80010010,WRITE,DMA2_MADR,t0,0x80010000\n0x80010014,WRITE,DMA2_BCR,t1,0x80010000\n0x80010018,WRITE,DMA2_CHCR,t2,0x80010000\n',encoding='utf-8')
    rows=load_hits(p); groups=rank(rows); lua,exact=lua_for(groups)
    assert len(exact)==3 and 'gaia_save24' in lua and 'DMA2_CHCR' in lua and 'r.GPR.n.t2' in lua
    print('B52R24 TRACE GENERATOR SELFTEST PASS')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('csv',nargs='?',type=Path); ap.add_argument('-o','--output',type=Path); ap.add_argument('--selftest',action='store_true'); a=ap.parse_args()
    if a.selftest:
        import tempfile
        with tempfile.TemporaryDirectory() as d:selftest(Path(d))
        return 0
    if not a.csv: ap.error('B52R23 GPU_MMIO_HITS.csv required')
    rows=load_hits(a.csv); groups=rank(rows)
    if not rows: raise RuntimeError('No writable GPU/DMA MMIO rows found')
    lua,exact=lua_for(groups); out=a.output or a.csv.with_name('GaiaMaster_B52R24_PCSX_DMA_SOURCE_CAPTURE.lua'); out.write_text(lua,encoding='utf-8')
    print(f'B52R24 generated {out} with {len(exact)} exact breakpoints across {min(16,len(groups))} ranked routines')
    return 0
if __name__=='__main__': raise SystemExit(main())
