#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv
from pathlib import Path

RAM=0x200000

def hx(s): return int(str(s).strip(),16)
def count16(v): return v if v else 0x10000

def load_events(p):
    out=[]
    with p.open('r',encoding='utf-8-sig',newline='') as f:
        for r in csv.DictReader(f,delimiter='\t'):
            r['_value']=hx(r['value']); out.append(r)
    return out

def find_tx(ev):
    starts=[i for i,e in enumerate(ev) if e['hw']=='DMA2_CHCR' and ((e['_value']>>24)&1)]
    if not starts: raise RuntimeError('No DMA2_CHCR start event')
    i=starts[-1]; madr=bcr=None
    for e in ev[:i+1]:
        if e['hw']=='DMA2_MADR': madr=e['_value']
        elif e['hw']=='DMA2_BCR': bcr=e['_value']
    if madr is None: raise RuntimeError('No DMA2_MADR before start')
    if bcr is None: bcr=0
    ch=ev[i]['_value']; sync=(ch>>9)&3; direction=ch&1; step=(ch>>1)&1
    return madr,bcr,ch,sync,direction,step

def watched_ranges(madr,bcr,sync,step):
    if sync==0: words=count16(bcr&0xffff)
    elif sync==1: words=count16(bcr&0xffff)*count16((bcr>>16)&0xffff)
    else: raise RuntimeError('SyncMode 2 is GPU command-list memory, not a linear DMA payload. Capture a SyncMode 0/1 transaction or use GPU-origin tracing.')
    words=min(words,RAM//4); n=words*4; m=madr&0x1fffff
    if step==0: start=m; end=m+n
    else: start=(m-(n-4))%RAM; end=start+n
    if end<=RAM: return [(start,n)],words
    first=RAM-start; return [(start,first),(0,n-first)],words

def make_lua(ranges,words,madr,bcr,ch,sync,direction,step):
    targets=[]
    for start,n in ranges:
        for base,label in ((0x80000000,'KSEG0'),(0xA0000000,'KSEG1')):
            targets.append((base|start,n,label))
    L=[
"-- Auto-generated by Gaia Master B52R25 writer-watch generator",
"gaia_b52r25_bps = gaia_b52r25_bps or {}",
"gaia_b52r25_events = {}",
"gaia_b52r25_armed = false",
"gaia_b52r25_skip_unique = 0",
"gaia_b52r25_last_pc = nil",
"local function h25(v) return string.upper(bit.tohex(tonumber(v),8)) end",
"",
"function gaia_arm25(skip_unique)",
"  gaia_b52r25_events={}; gaia_b52r25_last_pc=nil",
"  gaia_b52r25_skip_unique=tonumber(skip_unique or 0) or 0",
"  gaia_b52r25_armed=true",
"  print('GAIA B52R25 writer watch ARMED; skip_unique='..tostring(gaia_b52r25_skip_unique))",
"end",
"function gaia_disarm25() gaia_b52r25_armed=false; print('GAIA B52R25 disarmed') end",
"function gaia_next25() gaia_arm25(0); PCSX.resumeEmulator() end",
"",
"function gaia_save25(prefix)",
"  prefix=prefix or 'GaiaMaster_B52R25'",
"  local f=assert(io.open(prefix..'_WRITER_TRACE.tsv','wb'))",
"  f:write('seq\\taddress\\twidth\\tcause\\tpc\\tra\\tsp\\ta0\\ta1\\ta2\\ta3\\n')",
"  for i,e in ipairs(gaia_b52r25_events) do",
"    f:write(tostring(i)..'\\t'..h25(e.address)..'\\t'..tostring(e.width)..'\\t'..tostring(e.cause)..'\\t'..h25(e.pc)..'\\t'..h25(e.ra)..'\\t'..h25(e.sp)..'\\t'..h25(e.a0)..'\\t'..h25(e.a1)..'\\t'..h25(e.a2)..'\\t'..h25(e.a3)..'\\n')",
"  end",
"  f:close()",
"  local mem=PCSX.getMemPtr()",
"  local rf=assert(io.open(prefix..'_WRITER_RAM.bin','wb'))",
"  rf:write(ffi.string(mem,0x200000)); rf:close()",
"  print('Saved '..prefix..'_WRITER_TRACE.tsv + '..prefix..'_WRITER_RAM.bin')",
"end",
"",
"local targets={"
]
    for addr,n,label in targets:L.append(f"  {{addr=0x{addr:08X}, width=0x{n:X}, label='{label}'}},")
    L += ["}","for i,t in ipairs(targets) do",
"  gaia_b52r25_bps[i]=PCSX.addBreakpoint(t.addr,'Write',t.width,'Gaia B52R25 source-buffer writer '..t.label,function(address,width,cause)",
"    if not gaia_b52r25_armed then return end",
"    local ok,msg=pcall(function()",
"      local r=PCSX.getRegisters(); local pc=tonumber(r.pc)",
"      if gaia_b52r25_last_pc == pc then return end",
"      gaia_b52r25_last_pc=pc",
"      if gaia_b52r25_skip_unique > 0 then gaia_b52r25_skip_unique=gaia_b52r25_skip_unique-1; print('Skipped writer PC '..h25(pc)); return end",
"      local e={address=tonumber(address),width=tonumber(width),cause=tostring(cause),pc=pc,ra=tonumber(r.GPR.n.ra),sp=tonumber(r.GPR.n.sp),a0=tonumber(r.GPR.n.a0),a1=tonumber(r.GPR.n.a1),a2=tonumber(r.GPR.n.a2),a3=tonumber(r.GPR.n.a3)}",
"      gaia_b52r25_events[#gaia_b52r25_events+1]=e",
"      print('GAIA_B52R25 WRITER address='..h25(e.address)..' pc='..h25(e.pc)..' ra='..h25(e.ra)..' a0='..h25(e.a0)..' a1='..h25(e.a1)..' a2='..h25(e.a2)..' a3='..h25(e.a3))",
"      gaia_b52r25_armed=false; PCSX.pauseEmulator(); print('Paused. Run gaia_save25(); gaia_next25() catches the next distinct writer PC.')",
"    end)",
"    if not ok then print('GAIA_B52R25 callback error: '..tostring(msg)); gaia_b52r25_armed=false; PCSX.pauseEmulator() end",
"  end)",
"end",
"print('GAIA B52R25 loaded writer watches. Arm earlier than the target transition with gaia_arm25().')",
]
    meta=f"-- captured DMA: MADR=0x{madr:08X} BCR=0x{bcr:08X} CHCR=0x{ch:08X} sync={sync} direction={direction} step={step} words={words}\n"
    return meta+'\n'.join(L)+'\n'

def selftest():
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        p=Path(d)/'t.tsv'
        p.write_text('seq\tpc\tra\thw\treg\tvalue\tfunc_start\tscore\n1\t1\t2\tDMA2_MADR\tt0\t00001000\t0\t1\n2\t1\t2\tDMA2_BCR\tt1\t00010004\t0\t1\n3\t1\t2\tDMA2_CHCR\tt2\t01000201\t0\t1\n',encoding='utf-8')
        tx=find_tx(load_events(p)); ranges,words=watched_ranges(tx[0],tx[1],tx[3],tx[5]); lua=make_lua(ranges,words,*tx)
        assert ranges==[(0x1000,16)] and words==4 and 'PCSX.addBreakpoint' in lua and "'Write'" in lua and 'gaia_save25' in lua and '_WRITER_RAM.bin' in lua
    print('B52R25 WRITER WATCH GENERATOR SELFTEST PASS')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('trace',nargs='?',type=Path); ap.add_argument('-o','--output',type=Path); ap.add_argument('--selftest',action='store_true'); a=ap.parse_args()
    if a.selftest:selftest();return 0
    if not a.trace:ap.error('B52R24 TRACE.tsv required')
    tx=find_tx(load_events(a.trace)); ranges,words=watched_ranges(tx[0],tx[1],tx[3],tx[5]); lua=make_lua(ranges,words,*tx)
    out=a.output or a.trace.with_name('GaiaMaster_B52R25_PCSX_SOURCE_WRITER_WATCH.lua'); out.write_text(lua,encoding='utf-8')
    print(f'Generated {out}; ranges={ranges}; words={words}')
    return 0
if __name__=='__main__': raise SystemExit(main())
