#!/usr/bin/env python3
from __future__ import annotations
import argparse,csv
from pathlib import Path

RAM=0x200000

def hx(s): return int(str(s).strip(),16)
def count16(v): return v if v else 0x10000

def load_events(p):
    out=[]
    with p.open('r',encoding='utf-8-sig',newline='') as f:
        for r in csv.DictReader(f,delimiter='\t'):
            r['_value']=hx(r['value']); out.append(r)
    return out

def target_ranges(ev):
    starts=[i for i,e in enumerate(ev) if e['hw']=='DMA2_CHCR' and ((e['_value']>>24)&1)]
    if not starts: raise RuntimeError('No DMA2_CHCR start event in B52R24 trace')
    i=starts[-1]; madr=bcr=None
    for e in ev[:i+1]:
        if e['hw']=='DMA2_MADR': madr=e['_value']
        elif e['hw']=='DMA2_BCR': bcr=e['_value']
    if madr is None or bcr is None: raise RuntimeError('Missing DMA2 MADR/BCR before start')
    ch=ev[i]['_value']; sync=(ch>>9)&3; step=(ch>>1)&1
    if sync==0: words=count16(bcr&0xffff)
    elif sync==1: words=count16(bcr&0xffff)*count16((bcr>>16)&0xffff)
    else: raise RuntimeError('B52R28 requires a linear B52R24 target (DMA2 SyncMode 0/1); SyncMode 2 is command-list RAM')
    words=min(words,RAM//4); n=words*4; m=madr&0x1fffff
    if step==0: start=m
    else: start=(m-(n-4))%RAM
    if start+n<=RAM: ranges=[(start,n)]
    else: ranges=[(start,RAM-start),(0,n-(RAM-start))]
    return ranges,dict(madr=madr,bcr=bcr,chcr=ch,sync=sync,step=step,words=words)

def lua_for(ranges,meta):
    L=[
"-- Auto-generated by Gaia Master B52R28 CD-DMA provenance generator",
"-- Direct MMIO watches: CDROM host interface + DMA3 (CDROM).",
"gaia_b52r28_bps = gaia_b52r28_bps or {}",
"gaia_b52r28_events = {}",
"gaia_b52r28_armed = false",
"gaia_b52r28_bank = 0",
"gaia_b52r28_params = {}",
"gaia_b52r28_pending_lba = nil",
"gaia_b52r28_pending_msf = ''",
"gaia_b52r28_current_lba = nil",
"gaia_b52r28_lba_conf = 'UNKNOWN'",
"gaia_b52r28_read_cmd = 0",
"gaia_b52r28_reading = false",
"gaia_b52r28_madr = nil",
"gaia_b52r28_bcr = nil",
"gaia_b52r28_chcr = nil",
"gaia_b52r28_seq = 0",
"",
"local target_ranges = {"
]
    for start,n in ranges:L.append(f"  {{start=0x{start:X}, size=0x{n:X}}},")
    L += [
"}",
f"-- B52R24 target: MADR=0x{meta['madr']:08X} BCR=0x{meta['bcr']:08X} CHCR=0x{meta['chcr']:08X} sync={meta['sync']} step={meta['step']} words={meta['words']}",
"",
"local function h26(v) return string.upper(bit.tohex(tonumber(v or 0),8)) end",
"local function bcd26(v) return bit.rshift(v,4)*10 + bit.band(v,15) end",
"local function valid_bcd26(v) return bit.rshift(v,4) <= 9 and bit.band(v,15) <= 9 end",
"local function count16_26(v) if v == 0 then return 0x10000 else return v end end",
"local function split26(start,size)",
"  start=bit.band(start,0x1fffff)",
"  if start+size <= 0x200000 then return {{start=start,size=size}} end",
"  local first=0x200000-start",
"  return {{start=start,size=first},{start=0,size=size-first}}",
"end",
"local function overlap26(a0,an,b0,bn)",
"  local a1=a0+an; local b1=b0+bn",
"  local lo=math.max(a0,b0); local hi=math.min(a1,b1)",
"  if hi>lo then return hi-lo else return 0 end",
"end",
"local function target_overlap26(start,size)",
"  local total=0",
"  for _,d in ipairs(split26(start,size)) do",
"    for _,t in ipairs(target_ranges) do total=total+overlap26(d.start,d.size,t.start,t.size) end",
"  end",
"  return total",
"end",
"",
"local function insn26(r)",
"  local pc=tonumber(r.pc)",
"  if (pc>=0x80000000 and pc<0x80200000) or (pc>=0xA0000000 and pc<0xA0200000) or pc<0x00200000 then",
"    local off=bit.band(pc,0x1fffff); return tonumber(ffi.cast('uint32_t*',PCSX.getMemPtr()+off)[0])",
"  end",
"  if pc>=0xBFC00000 and pc<0xBFC80000 then",
"    local off=pc-0xBFC00000; return tonumber(ffi.cast('uint32_t*',PCSX.getRomPtr()+off)[0])",
"  end",
"  return nil",
"end",
"local function storeval26(r,width)",
"  local w=insn26(r); if w==nil then return nil,nil,nil end",
"  local op=bit.band(bit.rshift(w,26),0x3f); local rt=bit.band(bit.rshift(w,16),31)",
"  if op~=0x28 and op~=0x29 and op~=0x2b then return nil,w,rt end",
"  local v=tonumber(r.GPR.r[rt])",
"  if op==0x28 or width==1 then v=bit.band(v,0xff)",
"  elseif op==0x29 or width==2 then v=bit.band(v,0xffff) end",
"  return v,w,rt",
"end",
"",
"local function commit_command26(cmd,r)",
"  if gaia_b52r28_bank ~= 0 then gaia_b52r28_params={} return end",
"  if cmd==0x02 and #gaia_b52r28_params>=3 then",
"    local m=gaia_b52r28_params[1]; local s=gaia_b52r28_params[2]; local f=gaia_b52r28_params[3]",
"    if valid_bcd26(m) and valid_bcd26(s) and valid_bcd26(f) then",
"      local mm=bcd26(m); local ss=bcd26(s); local ff=bcd26(f)",
"      gaia_b52r28_pending_lba=(mm*60+ss)*75+ff-150",
"      gaia_b52r28_pending_msf=string.format('%02X:%02X:%02X',m,s,f)",
"      print('GAIA_B52R28 Setloc '..gaia_b52r28_pending_msf..' LBA='..tostring(gaia_b52r28_pending_lba))",
"    end",
"  elseif cmd==0x06 or cmd==0x1b then",
"    gaia_b52r28_read_cmd=cmd; gaia_b52r28_reading=true",
"    if gaia_b52r28_pending_lba~=nil then",
"      gaia_b52r28_current_lba=gaia_b52r28_pending_lba; gaia_b52r28_lba_conf='SETLOC_START'",
"      gaia_b52r28_pending_lba=nil",
"    else gaia_b52r28_lba_conf='CONTINUE_UNKNOWN' end",
"    print(string.format('GAIA_B52R28 Read command %02X current_lba=%s',cmd,tostring(gaia_b52r28_current_lba)))",
"  elseif cmd==0x08 or cmd==0x09 then",
"    gaia_b52r28_reading=false",
"  end",
"  gaia_b52r28_params={}",
"end",
"",
"local function mmio26(which,address,width,cause)",
"  if not gaia_b52r28_armed then return end",
"  local ok,msg=pcall(function()",
"    local r=PCSX.getRegisters(); local v,w,rt=storeval26(r,width)",
"    if v==nil then print('GAIA_B52R28 cannot decode store at pc='..h26(r.pc)); return end",
"    if which=='CD_BANK' then gaia_b52r28_bank=bit.band(v,3)",
"    elseif which=='CD_PARAM' then if gaia_b52r28_bank==0 then gaia_b52r28_params[#gaia_b52r28_params+1]=bit.band(v,0xff) end",
"    elseif which=='CD_CMD' then commit_command26(bit.band(v,0xff),r)",
"    elseif which=='DMA3_MADR' then gaia_b52r28_madr=v",
"    elseif which=='DMA3_BCR' then gaia_b52r28_bcr=v",
"    elseif which=='DMA3_CHCR' then",
"      gaia_b52r28_chcr=v",
"      local start=bit.band(bit.rshift(v,24),1)",
"      if start==1 and gaia_b52r28_madr~=nil and gaia_b52r28_bcr~=nil then",
"        local sync=bit.band(bit.rshift(v,9),3); local dir=bit.band(v,1); local words=0",
"        if sync==0 then words=count16_26(bit.band(gaia_b52r28_bcr,0xffff))",
"        elseif sync==1 then words=count16_26(bit.band(gaia_b52r28_bcr,0xffff))*count16_26(bit.band(bit.rshift(gaia_b52r28_bcr,16),0xffff)) end",
"        local bytes=words*4; local dest=bit.band(gaia_b52r28_madr,0x1fffff); local ov=target_overlap26(dest,bytes)",
"        gaia_b52r28_seq=gaia_b52r28_seq+1",
"        local e={seq=gaia_b52r28_seq,pc=tonumber(r.pc),ra=tonumber(r.GPR.n.ra),sp=tonumber(r.GPR.n.sp),madr=gaia_b52r28_madr,bcr=gaia_b52r28_bcr,chcr=v,sync=sync,dir=dir,dest=dest,bytes=bytes,overlap=ov,lba=gaia_b52r28_current_lba,conf=gaia_b52r28_lba_conf,cmd=gaia_b52r28_read_cmd,msf=gaia_b52r28_pending_msf}",
"        gaia_b52r28_events[#gaia_b52r28_events+1]=e",
"        print(string.format('GAIA_B52R28 DMA3 seq=%d dest=%06X bytes=%d overlap=%d LBA=%s conf=%s pc=%s',e.seq,e.dest,e.bytes,e.overlap,tostring(e.lba),e.conf,h26(e.pc)))",
"        if gaia_b52r28_reading and gaia_b52r28_current_lba~=nil and bytes>0 then",
"          local sectors=nil",
"          if bytes%2048==0 then sectors=bytes/2048 elseif bytes%2352==0 then sectors=bytes/2352 end",
"          if sectors~=nil then gaia_b52r28_current_lba=gaia_b52r28_current_lba+sectors; gaia_b52r28_lba_conf='SEQUENTIAL_TRACKED' else gaia_b52r28_lba_conf='UNSIZED_CONTINUE' end",
"        end",
"        if ov>0 then gaia_b52r28_armed=false; PCSX.pauseEmulator(); print('DIRECT DMA3/TARGET OVERLAP. Run gaia_save26() now.') end",
"      end",
"    end",
"  end)",
"  if not ok then print('GAIA_B52R28 callback error: '..tostring(msg)); gaia_b52r28_armed=false; PCSX.pauseEmulator() end",
"end",
"",
"function gaia_arm26() gaia_b52r28_events={}; gaia_b52r28_seq=0; gaia_b52r28_armed=true; print('GAIA B52R28 ARMED before target transition') end",
"function gaia_disarm26() gaia_b52r28_armed=false; print('GAIA B52R28 disarmed') end",
"function gaia_save26(prefix)",
"  prefix=prefix or 'GaiaMaster_B52R28'",
"  local f=assert(io.open(prefix..'_CD_DMA_TRACE.tsv','wb'))",
"  f:write('seq\\tpc\\tra\\tsp\\tmadr\\tbcr\\tchcr\\tsync\\tdirection\\tdest_start\\tdest_bytes\\toverlap_bytes\\tlba\\tlba_conf\\tread_cmd\\tsetloc_msf\\n')",
"  for _,e in ipairs(gaia_b52r28_events) do",
"    f:write(tostring(e.seq)..'\\t'..h26(e.pc)..'\\t'..h26(e.ra)..'\\t'..h26(e.sp)..'\\t'..h26(e.madr)..'\\t'..h26(e.bcr)..'\\t'..h26(e.chcr)..'\\t'..tostring(e.sync)..'\\t'..tostring(e.dir)..'\\t'..string.format('%06X',e.dest)..'\\t'..tostring(e.bytes)..'\\t'..tostring(e.overlap)..'\\t'..tostring(e.lba or -1)..'\\t'..e.conf..'\\t'..string.format('%02X',e.cmd or 0)..'\\t'..tostring(e.msf or '')..'\\n')",
"  end",
"  f:close(); print('Saved '..prefix..'_CD_DMA_TRACE.tsv')",
"end",
"",
"local defs={{0x1F801800,'CD_BANK'},{0x1F801801,'CD_CMD'},{0x1F801802,'CD_PARAM'},{0x1F8010B0,'DMA3_MADR'},{0x1F8010B4,'DMA3_BCR'},{0x1F8010B8,'DMA3_CHCR'}}",
"for i,d in ipairs(defs) do",
"  gaia_b52r28_bps[i]=PCSX.addBreakpoint(d[1],'Write',4,'Gaia B52R28 '..d[2],function(address,width,cause) mmio26(d[2],address,width,cause) end)",
"end",
"print('GAIA B52R28 loaded. Call gaia_arm26() before entering the target menu.')",
]
    return '\n'.join(L)+'\n'

def selftest():
    rows=[
      {'hw':'DMA2_MADR','_value':0x1000},
      {'hw':'DMA2_BCR','_value':0x00010004},
      {'hw':'DMA2_CHCR','_value':0x01000201},
    ]
    r,m=target_ranges(rows)
    assert r==[(0x1000,16)] and m['sync']==1 and 'DMA3_CHCR' in lua_for(r,m) and 'Setloc' in lua_for(r,m)
    print('B52R28 CD DMA PROVENANCE GENERATOR SELFTEST PASS')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('trace',nargs='?',type=Path); ap.add_argument('-o','--output',type=Path); ap.add_argument('--selftest',action='store_true'); a=ap.parse_args()
    if a.selftest:selftest();return 0
    if not a.trace:ap.error('B52R24 TRACE.tsv required')
    ranges,meta=target_ranges(load_events(a.trace))
    out=a.output or a.trace.with_name('GaiaMaster_B52R28_PCSX_CD_DMA_PROVENANCE.lua')
    out.write_text(lua_for(ranges,meta),encoding='utf-8')
    print(f'Generated {out}; target_ranges={ranges}')
    return 0
if __name__=='__main__': raise SystemExit(main())
